### ISSUE TITLE
wrong handling of negative zero temperature

### ISSUE THREAD

**Issue by kriss2013** [eiannone/LacrosseReceiver#1]
Hi there,

first thanx for the nice library. I used it in my project and it works fine. nevertheless I have 2 issues for you. Here the first one.

at the end of timing2measure.cpp you have some code to convert sensor temperature less than 50 to a negative number. The code works Ok for temperature below -1 and above 0 but NOT in between. After some analysis the reason is clear: when you increment m.units by one you introduce a degeneracy for this measure range, meaning your code returns 0.2 for both 49.8 and 50.2. the code should return "-0" for the first case, but it is not possible with an int8_t. 

This way the calling function has no way to correct the wrong value. For my part I will enhance your measure struct with a bool negZero only for this range. my calling code will have more work ;-) a marginal better way would be to calculate a display string right away and return it, but should we use "." or "," as separator? it depends on the locale, not nice. We could also calculate a float right away, but it seems overkill. maybe you can come to a better idea!

**Comment by eiannone** [comment]
Thank you @kriss2013 , you're absolutely right! 
The `measure` struct currently cannot handle negative values between -1 and 0.

Yeah, using a float would be overkill, and not so easy to manage on Arduino (for example when converting to a formatted string).
Maybe it would be better to use a `sign` property, like your `negZero`. Perhaps it could be an _int8_t_ which can be -1 for negative values and +1 for positive ones. The `units` property then would be used as an absolute value.

**Comment by eiannone** [comment]
This should be fixed now

**Comment by kriss2013** [comment]
I have your code running for several days now and the external temperature went through the range under consideration. It seems to work properly now

**Comment by eiannone** [comment]
Great!
