### ISSUE TITLE
Conflict when more than one sensor are sending

### ISSUE THREAD

**Issue by kriss2013** [eiannone/LacrosseReceiver#2]
Hi,

here the second issue.

I have 4 sensors sending in my neighbourhood, 2 are mine 2 not (I have no influence on them). The result is that from time to tim eI see a collision and measures get mixed. It is no very often, but I save all measure in a DB and it occurs a couple of time per day. 

I changed your code to be more strict and expect exactly 44 bits (I use TX3) moreover I use checksum. This seems to vastly improve the situation (no errors after 2 days)

maybe you could introduce a "strict" parameter to do so? or introduce a "sensorId" parameter and when it is used, be strict. The responsability of any wrapping code would be to get this Id (they are changed when battery are changed)

**Comment by eiannone** [comment]
Hi, I made some changes to the code, could you try it now and tell me if solves the problem?
I think that using checksum should be enough to exclude mixed packets. I have now set the checksum control enabled by default.

Regarding your filter on the number of bits, it surely helps to filter corrupted packets, but you could loose also some legitimate ones, which contain only some noise.

**Comment by kriss2013** [comment]
I will change my code accordingly, I will let the result runs for a couple of days and I will tell you the result. Thanx for the lib and your support of it!

**Comment by kriss2013** [comment]
after several days of testing, I got no instances of sensor mix. I think your change works .

**Comment by eiannone** [comment]
Ok, thank you very much.
